[WIP] Failed: WorkManager Hilt injection issue (NoSuchMethodException) and Room(not tested)
This commit saves the current state where the WorkManager setup is failing due to a Hilt/WorkerFactory misconfiguration. The whole application doesn't crash but normally function as without WorkManager.

Originally attempt to implement WorkManager/Room of downloading data in background and then notification is currently failing. Needs deep investigation. (Seems that the part of Room is functionable, but not completely checked.)

Detailed error trace:
Could not instantiate com.example.geminispotifyapp.data.worker.SpotifyMetadataWorker
java.lang.NoSuchMethodException: com.example.geminispotifyapp.data.worker.SpotifyMetadataWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
	at java.lang.Class.getConstructor0(Class.java:3385)
	at java.lang.Class.getDeclaredConstructor(Class.java:3067)
	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback$fallbackToReflection(WorkerFactory.kt:87)
	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.kt:96)
	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.kt:234)
	at androidx.work.impl.WorkerWrapper.access$runWorker(WorkerWrapper.kt:67)
	at androidx.work.impl.WorkerWrapper$launch$1$resolution$1.invokeSuspend(WorkerWrapper.kt:98)
	at androidx.work.impl.WorkerWrapper$launch$1$resolution$1.invoke(Unknown Source:8)
	at androidx.work.impl.WorkerWrapper$launch$1$resolution$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at androidx.work.impl.WorkerWrapper$launch$1.invokeSuspend(WorkerWrapper.kt:98)
	at androidx.work.impl.WorkerWrapper$launch$1.invoke(Unknown Source:8)
	at androidx.work.impl.WorkerWrapper$launch$1.invoke(Unknown Source:4)
	at androidx.work.ListenableFutureKt$launchFuture$1$2.invokeSuspend(ListenableFuture.kt:42)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
	at java.lang.Thread.run(Thread.java:1119)
Could not create Worker com.example.geminispotifyapp.data.worker.SpotifyMetadataWorker

Will revert main branch and use Firebase/FCM as a temporary replacement.